using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Tokens;
using RestaurantManagement.Application.DTOs.Auth;
using RestaurantManagement.Application.Interfaces;
using RestaurantManagement.Domain.Entities;

namespace RestaurantManagement.Application.Services;

/// <summary>
/// Authentication service handling user registration, login, JWT token
/// generation, and password management workflows.
///
/// Key security features:
///   - Passwords are hashed using ASP.NET Identity's PasswordHasher (PBKDF2)
///   - JWT tokens include sub, email, and role claims signed with HMAC-SHA256
///   - First-login users must change their temporary password before receiving a token
///   - Activation codes have configurable expiration windows
/// </summary>

public sealed class AuthService : IAuthService
{
    private readonly IAppDbContext _db;
    private readonly IConfiguration _config;
    private readonly PasswordHasher<User> _hasher = new();

    public AuthService(IAppDbContext db, IConfiguration config)
    {
        _db = db;
        _config = config;
    }

    public async Task<AuthResponseDto> RegisterAsync(RegisterRequestDto dto, CancellationToken ct = default)
    {
        var email = dto.Email.Trim().ToLowerInvariant();

        var exists = await _db.Users.AnyAsync(u => u.Email.ToLower() == email, ct);
        if (exists) throw new InvalidOperationException("Email is already registered.");

        // Default role
        var roleName = string.IsNullOrWhiteSpace(dto.RoleName) ? "Waiter" : dto.RoleName.Trim();
        var role = await _db.Roles.FirstOrDefaultAsync(r => r.RoleName == roleName, ct);

        // If the specified role doesn't exist, fall back to "Waiter" as default
        role ??= await _db.Roles.FirstOrDefaultAsync(r => r.RoleName == "Waiter", ct)
                 ?? throw new InvalidOperationException("Default role not found (Waiter). Seed roles first.");

        var user = new User
        {
            FirstName = dto.FirstName.Trim(),
            LastName = dto.LastName.Trim(),
            Email = dto.Email.Trim().ToLowerInvariant(),
            RoleId = role.RoleId,
            IsActive = true,
            PasswordHash = "" // Will be set below after user entity is created
        };

        user.PasswordHash = _hasher.HashPassword(user, dto.Password);

        _db.Users.Add(user);
        await _db.SaveChangesAsync(ct);

        // To access user.Role.RoleName, the Role navigation property must be loaded.
        // Since it's not loaded during user creation, we use the 'role' object directly.
        var accessToken = GenerateJwt(user.UserId, user.Email, role.RoleName);

        return new AuthResponseDto(
            accessToken,
            new AuthUserDto(user.UserId, user.FirstName, user.LastName, user.Email, role.RoleName, user.PhoneNumber, user.Country, user.City, user.PostalCode, user.TaxId)
        );
    }

    public async Task<LoginResult> LoginAsync(LoginRequestDto dto, CancellationToken ct = default)
    {
        var email = dto.Email.Trim().ToLowerInvariant();

        var user = await _db.Users
            .Include(u => u.Role)
            .FirstOrDefaultAsync(u => u.Email.ToLower() == email, ct);

        if (user is null) throw new UnauthorizedAccessException("Invalid credentials.");
        if (!user.IsActive) throw new UnauthorizedAccessException("User is inactive.");

        // User must have a password set (temp password generated by admin)
        if (string.IsNullOrEmpty(user.PasswordHash))
            throw new UnauthorizedAccessException("No password set. Ask your administrator to generate a temporary password.");

        var result = _hasher.VerifyHashedPassword(user, user.PasswordHash, dto.Password);
        if (result == PasswordVerificationResult.Failed)
            throw new UnauthorizedAccessException("Invalid credentials.");

        // First-login: force password change
        if (user.IsFirstLogin)
        {
            return new LoginResult(
                RequiresPasswordChange: true,
                Auth: null,
                ActivationCode: user.ActivationCode,
                Email: user.Email
            );
        }

        var roleName = user.Role?.RoleName ?? "Unknown";
        var accessToken = GenerateJwt(user.UserId, user.Email, roleName);

        // Record last login timestamp
        user.LastLoginAt = DateTime.UtcNow;
        await _db.SaveChangesAsync(ct);

        return new LoginResult(
            RequiresPasswordChange: false,
            Auth: new AuthResponseDto(
                accessToken,
                new AuthUserDto(user.UserId, user.FirstName, user.LastName, user.Email, roleName, user.PhoneNumber, user.Country, user.City, user.PostalCode, user.TaxId)
            ),
            ActivationCode: null,
            Email: null
        );
    }

    public async Task<AuthResponseDto> ChangePasswordAsync(ChangePasswordRequestDto dto, CancellationToken ct = default)
    {
        if (dto.NewPassword != dto.ConfirmPassword)
            throw new ArgumentException("New password and confirmation do not match.");

        if (string.IsNullOrWhiteSpace(dto.NewPassword) || dto.NewPassword.Length < 6)
            throw new ArgumentException("New password must be at least 6 characters.");

        var email = dto.Email.Trim().ToLowerInvariant();
        var user = await _db.Users
            .Include(u => u.Role)
            .FirstOrDefaultAsync(u => u.Email.ToLower() == email, ct);

        if (user is null) throw new UnauthorizedAccessException("User not found.");
        if (!user.IsFirstLogin) throw new InvalidOperationException("Password change is not required for this account.");

        if (user.ActivationCode != dto.ActivationCode)
            throw new UnauthorizedAccessException("Invalid temporary password.");

        if (user.ActivationCodeExpiry.HasValue && user.ActivationCodeExpiry.Value < DateTime.UtcNow)
            throw new InvalidOperationException("Temporary password has expired. Ask your administrator to generate a new one.");

        // Set real password
        user.PasswordHash = _hasher.HashPassword(user, dto.NewPassword);
        user.IsFirstLogin = false;
        user.ActivationCode = null;
        user.ActivationCodeExpiry = null;

        await _db.SaveChangesAsync(ct);

        var roleName = user.Role?.RoleName ?? "Unknown";
        var accessToken = GenerateJwt(user.UserId, user.Email, roleName);

        return new AuthResponseDto(
            accessToken,
            new AuthUserDto(user.UserId, user.FirstName, user.LastName, user.Email, roleName, user.PhoneNumber, user.Country, user.City, user.PostalCode, user.TaxId)
        );
    }

    public async Task<bool> UpdatePasswordAsync(int userId, UpdatePasswordRequestDto dto, CancellationToken ct = default)
    {
        if (dto.NewPassword != dto.ConfirmPassword)
            throw new ArgumentException("New password and confirmation do not match.");

        if (string.IsNullOrWhiteSpace(dto.NewPassword) || dto.NewPassword.Length < 6)
            throw new ArgumentException("New password must be at least 6 characters.");

        var user = await _db.Users.FirstOrDefaultAsync(u => u.UserId == userId, ct);
        if (user is null) throw new UnauthorizedAccessException("User not found.");

        if (string.IsNullOrEmpty(user.PasswordHash))
            throw new UnauthorizedAccessException("Password cannot be updated. Use first login flow.");

        var result = _hasher.VerifyHashedPassword(user, user.PasswordHash, dto.CurrentPassword);
        if (result == PasswordVerificationResult.Failed)
            throw new UnauthorizedAccessException("Current password is incorrect.");

        user.PasswordHash = _hasher.HashPassword(user, dto.NewPassword);
        await _db.SaveChangesAsync(ct);
        return true;
    }

    private string GenerateJwt(int userId, string email, string roleName)
    {
        var jwtSection = _config.GetSection("Jwt");
        var key = jwtSection["Key"]!;
        var issuer = jwtSection["Issuer"]!;
        var audience = jwtSection["Audience"]!;
        var expiresMinutes = int.Parse(jwtSection["ExpiresMinutes"] ?? "120");

        var claims = new List<Claim>
        {
            new(JwtRegisteredClaimNames.Sub, userId.ToString()),
            new(JwtRegisteredClaimNames.Email, email),
            new(ClaimTypes.Role, roleName),
            new("role", roleName) // Duplicated without namespace prefix for easy frontend parsing
        };

        var signingKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(key));
        var creds = new SigningCredentials(signingKey, SecurityAlgorithms.HmacSha256);

        var token = new JwtSecurityToken(
            issuer: issuer,
            audience: audience,
            claims: claims,
            expires: DateTime.UtcNow.AddMinutes(expiresMinutes),
            signingCredentials: creds
        );

        return new JwtSecurityTokenHandler().WriteToken(token);
    }
}
